In [1]:
import pandas as pd
from pathlib import Path

In [2]:
base_dir = Path("../data/imdb")

In [3]:
basics = pd.read_csv(base_dir/"title.basics.tsv",sep="\t",low_memory=False)
print("Origibal basicis shape:",basics.shape)
basics.head()

Origibal basicis shape: (12293734, 9)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [4]:
movies = basics[basics["titleType"] == "movie"]
print("Movies only shape:",movies.shape)

Movies only shape: (738068, 9)

In [6]:
movies = movies[["tconst","primaryTitle","originalTitle","startYear","runtimeMinutes","genres","isAdult"]]

In [7]:
movies.isnull().sum()

tconst            0
primaryTitle      3
originalTitle     3
startYear         0
runtimeMinutes    0
genres            0
isAdult           0
dtype: int64

In [9]:
movies = movies.replace("\\N",pd.NA)

In [14]:
movies = movies.dropna(subset=["tconst","primaryTitle","startYear"])

In [15]:
movies["startYear"] = pd.to_numeric(movies["startYear"],errors="coerce")
movies["runtimeMinutes"] = pd.to_numeric(movies["runtimeMinutes"],errors="coerce")

In [16]:
print("Final movies shape:",movies.shape)
movies.head()

Final movies shape: (627592, 7)

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult
8,tt0000009,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
144,tt0000147,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897.0,100.0,"Documentary,News,Sport",0
498,tt0000502,Bohemios,Bohemios,1905.0,100.0,<NA>,0
570,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906.0,70.0,"Action,Adventure,Biography",0
587,tt0000591,The Prodigal Son,L'enfant prodigue,1907.0,90.0,Drama,0

In [17]:
movies.isnull().sum()

tconst                 0
primaryTitle           0
originalTitle          0
startYear              0
runtimeMinutes    170241
genres             70737
isAdult                0
dtype: int64

In [20]:
output_dir =Path("../data/processed")
output_dir.mkdir(exist_ok=True)

movies.to_csv(
    output_dir / "imdb_movies.csv",
    index=False
)

print("imdb_movies dataset saved.")

imdb_movies dataset saved.