In [1]:
import pandas as pd
from pathlib import Path

In [2]:
base_dir = Path("../data/imdb")

In [5]:
basics = pd.read_csv(base_dir/ "title.basics.tsv" ,sep="\t",low_memory=False)
principals = pd.read_csv(base_dir/ "title.principals.tsv" ,sep="\t",low_memory=False)
names = pd.read_csv(base_dir/ "name.basics.tsv" ,sep="\t",low_memory=False)
ratings = pd.read_csv(base_dir/ "title.ratings.tsv" ,sep="\t",low_memory=False)

In [6]:
print(basics.shape)
print(principals.shape)
print(names.shape)
print(ratings.shape)

(12293734, 9)
(97836504, 6)
(15092471, 6)
(1635941, 3)

In [17]:
basics.isnull().sum()

tconst              0
titleType           0
primaryTitle       25
originalTitle      25
isAdult             0
startYear           0
endYear             0
runtimeMinutes      0
genres            528
dtype: int64

In [18]:
principals.isnull().sum()

tconst        0
ordering      0
nconst        0
category      0
job           0
characters    0
dtype: int64

In [19]:
names.isnull().sum()

nconst                0
primaryName          11
birthYear             0
deathYear             0
primaryProfession     0
knownForTitles        0
dtype: int64

In [20]:
ratings.isnull().sum()

tconst           0
averageRating    0
numVotes         0
dtype: int64

In [41]:
basics.head(20)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
5,tt0000006,short,Chinese Opium Den,Chinese Opium Den,0,1894,\N,1,Short
6,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport"
7,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short"
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance
9,tt0000010,short,Leaving the Factory,La sortie de l'usine Lumière à Lyon,0,1895,\N,1,"Documentary,Short"
10,tt0000011,short,Akrobatisches Potpourri,Akrobatisches Potpourri,0,1895,\N,1,"Documentary,Short"
11,tt0000012,short,The Arrival of a Train,L'arrivée d'un train à La Ciotat,0,1896,\N,1,"Documentary,Short"
12,tt0000013,short,The Photographical Congress Arrives in Lyon,Le débarquement du congrès de photographie à Lyon,0,1895,\N,1,"Documentary,Short"
13,tt0000014,short,The Waterer Watered,L'arroseur arrosé,0,1895,\N,1,"Comedy,Short"
14,tt0000015,short,Around a Cabin,Autour d'une cabine,0,1894,\N,2,"Animation,Comedy,Short"
15,tt0000016,short,Boat Leaving the Port,Barque sortant du port,0,1895,\N,1,"Documentary,Short"
16,tt0000017,short,Italienischer Bauerntanz,Italienischer Bauerntanz,0,1895,\N,1,"Documentary,Short"
17,tt0000018,short,Das boxende Känguruh,Das boxende Känguruh,0,1895,\N,1,"Short,Sport"
18,tt0000019,short,The Clown Barber,The Clown Barber,0,1898,\N,\N,"Comedy,Short"
19,tt0000020,short,The Derby 1895,The Derby 1895,0,1895,\N,1,"Documentary,Short,Sport"

In [9]:
basics.columns

Index(['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'genres'],
      dtype='object')

In [43]:
principals.head(20)

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N
5,tt0000002,2,nm1335271,composer,\N,\N
6,tt0000003,1,nm0721526,director,\N,\N
7,tt0000003,2,nm0721526,writer,\N,\N
8,tt0000003,3,nm1770680,producer,producer,\N
9,tt0000003,4,nm0721526,producer,producer,\N
10,tt0000003,5,nm1335271,composer,\N,\N
11,tt0000003,6,nm5442200,editor,editor,\N
12,tt0000004,1,nm0721526,director,\N,\N
13,tt0000004,2,nm1335271,composer,\N,\N
14,tt0000005,1,nm0443482,actor,\N,"[""Blacksmith""]"
15,tt0000005,2,nm0653042,actor,\N,"[""Assistant""]"
16,tt0000005,3,nm0249379,producer,producer,\N
17,tt0000007,1,nm0179163,actor,\N,\N
18,tt0000007,2,nm0183947,actor,\N,\N
19,tt0000007,3,nm0005690,director,\N,\N

In [11]:
principals.columns

Index(['tconst', 'ordering', 'nconst', 'category', 'job', 'characters'], dtype='object')

In [13]:
names.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0117057"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"

In [14]:
names.columns

Index(['nconst', 'primaryName', 'birthYear', 'deathYear', 'primaryProfession',
       'knownForTitles'],
      dtype='object')

In [15]:
ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2192
1  tt0000002            5.5       309
2  tt0000003            6.5      2296
3  tt0000004            5.1       196
4  tt0000005            6.2      3028

In [16]:
ratings.columns

Index(['tconst', 'averageRating', 'numVotes'], dtype='object')

In [38]:
movies = basics[basics["titleType"] == "movie"]
movies = movies[["tconst","primaryTitle","startYear","genres"]]
movies = movies.dropna()
movies.shape

(738065, 4)

In [39]:
movies.head()

,tconst,primaryTitle,startYear,genres
8,tt0000009,Miss Jerry,1894,Romance
144,tt0000147,The Corbett-Fitzsimmons Fight,1897,"Documentary,News,Sport"
498,tt0000502,Bohemios,1905,\N
570,tt0000574,The Story of the Kelly Gang,1906,"Action,Adventure,Biography"
587,tt0000591,The Prodigal Son,1907,Drama

In [31]:
actors = principals[principals["category"].isin(["actor","actress"])]
actors = actors[["tconst","nconst"]]
print("Actor-movie relationships: ",actors.shape)

Actor-movie relationships:  (40608548, 2)

In [32]:
actors.head()

       tconst     nconst
14  tt0000005  nm0443482
15  tt0000005  nm0653042
17  tt0000007  nm0179163
18  tt0000007  nm0183947
24  tt0000008  nm0653028

In [33]:
actors = actors.merge(
    names[["nconst","primaryName"]],
    on="nconst",
    how="left"
)
actors = actors.rename(columns={"primaryName":"actor_name"})
actors.head()

      tconst     nconst        actor_name
0  tt0000005  nm0443482    Charles Kayser
1  tt0000005  nm0653042          John Ott
2  tt0000007  nm0179163  James J. Corbett
3  tt0000007  nm0183947    Peter Courtney
4  tt0000008  nm0653028          Fred Ott

In [34]:
actor_movies = actors.merge(
    movies,
    on="tconst",
    how="inner"
)
print("Actor-movie dataset:",actor_movies.shape)

Actor-movie dataset: (4058946, 5)

In [35]:
actor_movies.head()

      tconst     nconst         actor_name primaryTitle startYear
0  tt0000009  nm0063086    Blanche Bayliss   Miss Jerry      1894
1  tt0000009  nm0183823  William Courtenay   Miss Jerry      1894
2  tt0000009  nm1309758     Chauncey Depew   Miss Jerry      1894
3  tt0000502  nm0215752   Antonio del Pozo     Bohemios      1905
4  tt0000502  nm0252720        El Mochuelo     Bohemios      1905

In [36]:
actor_movies = actor_movies.merge(
    ratings,
    on="tconst",
    how="left"
)
actor_movies.head()

,tconst,nconst,actor_name,primaryTitle,startYear,averageRating,numVotes
0,tt0000009,nm0063086,Blanche Bayliss,Miss Jerry,1894,5.3,234.0
1,tt0000009,nm0183823,William Courtenay,Miss Jerry,1894,5.3,234.0
2,tt0000009,nm1309758,Chauncey Depew,Miss Jerry,1894,5.3,234.0
3,tt0000502,nm0215752,Antonio del Pozo,Bohemios,1905,3.3,25.0
4,tt0000502,nm0252720,El Mochuelo,Bohemios,1905,3.3,25.0

In [37]:
actor_movies.shape

(4058946, 7)